// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "model": string;
      "customBaseURL": string;
      "uvPath": string;
      "backend": string;
      "sourceLanguage": string;
      "targetLanguage": string;
    };
  }
}
